sudo: required
language: python
services:
- docker

script:
- docker image build -t kobikah/docker-flask-test1 .

after_success:
  #log in to docker CLI
  - echo "Dockerhubhub!01" | docker login -u "kobikah" --password-stdin
  #take built images and push to DOcker hub
  - docker push kobikah/docker-flask-test1
  #test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Dockertest-env"
  env: "dtest"
  bucket_name: "elasticbeanstalk-us-east-2-114073191308"
  on:
  branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY